export const FINES_REPORTS_REPORT_SUMMARY_CRITERIA_LABELS = {
  reportType: 'Report Type',
  enforcement: 'Enforcement',
  actionDate: 'Action date',
  accountType: 'Account type',
  accountStatus: 'Account status',
  collectionOrder: 'Collection order',
  minimumAccountBalance: 'Minimum account balance',
  maximumAccountBalance: 'Maximum account balance',
  lowerNameRange: 'Lower name range',
  upperNameRange: 'Upper name range',
  paymentMethod: 'Payment method',
  paymentDate: 'Payment date',
  minimumPaymentAmount: 'Minimum payment amount',
  maximumPaymentAmount: 'Maximum payment amount',
  paymentsMade: 'Payments made',
  paymentReportMode: 'Payment report mode',
  sinceLastEnforcementAction: 'Since last enforcement action',
  sinceDate: 'Since date',
  firstPaymentOrPayByInNext7Days: 'Only accounts with initial or full payment due in the next 7 days',
} as const;
