import { FINES_REPORTS_REPORT_SUMMARY_STATUSES } from './fines-reports-report-summary-statuses.constant';

export const FINES_REPORTS_REPORT_SUMMARY_RECORD_COUNT_DASH_STATUSES = [
  FINES_REPORTS_REPORT_SUMMARY_STATUSES.requested,
  FINES_REPORTS_REPORT_SUMMARY_STATUSES.inProgress,
  FINES_REPORTS_REPORT_SUMMARY_STATUSES.error,
] as const;
