import { IOpalFinesCache } from '../interfaces/opal-fines-cache.interface';

export const OPAL_FINES_CACHE_DEFAULTS: IOpalFinesCache = {
  courtRefDataCache$: {},
  businessUnitsCache$: null,
  businessUnitsPermissionCache$: {},
  localJusticeAreasCache$: null,
  localJusticeAreasLjaTypeCache$: {},
  resultsCache$: {},
  resultCache$: {},
  offenceCodesCache$: {},
  majorCreditorsCache$: {},
  draftAccountsCache$: {},
  prosecutorDataCache$: {},
  defendantAccountAtAGlanceCache$: null,
  defendantAccountPartyCache$: null,
  defendantAccountParentOrGuardianAccountPartyCache$: null,
  defendantAccountEnforcementCache$: null,
  defendantAccountImpositionsCache$: null,
  defendantAccountHistoryAndNotesCache$: null,
  defendantAccountPaymentTermsLatestCache$: null,
  defendantAccountFixedPenaltyCache$: null,
  minorCreditorAccountAtAGlanceCache$: null,
  minorCreditorAccountCreditorCache$: null,
  enforcersCache$: null,
};
