import { IOpalFinesCourtRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-court-ref-data.interface';
import { IOpalFinesLocalJusticeAreaRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-local-justice-area-ref-data.interface';
import { IOpalFinesMajorCreditorRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-major-creditor-ref-data.interface';
import { IOpalFinesOffencesRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-offences-ref-data.interface';
import { IOpalFinesProsecutorRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-prosecutor-ref-data.interface';
import { IOpalFinesResultRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-result-ref-data.interface';
import { IOpalFinesResultsRefData } from '@services/fines/opal-fines-service/interfaces/opal-fines-results-ref-data.interface';

export const BUSINESS_UNIT_77_MOCK = {
  businessUnitId: 77,
  businessUnitName: 'Camberwell Green',
  businessUnitCode: '0046',
  businessUnitType: 'Accounting Division',
  accountNumberPrefix: null,
  opalDomain: 'Fines',
  welshLanguage: false,
  parentBusinessUnit: {
    businessUnitId: 1001,
    businessUnitName: 'Greater London',
    businessUnitCode: '01',
    businessUnitType: 'Area',
    accountNumberPrefix: null,
    opalDomain: null,
    welshLanguage: false,
    parentBusinessUnit: null,
    configurationItems: [],
  },
  configurationItems: [],
};

export const OPAL_OFFENCE_BY_ID_MOCK = [
  {
    offenceId: 47883,
    businessUnitId: null,
    cjsCode: 'CD09019',
    offenceTitle:
      'Carrier - vehicle carrying dangerous / pressurised goods with an inadequacy of fire extinguishers on the vehicle',
    offenceTitleCy: null,
    dateUsedFrom: '2009-07-01T00:00:00',
    dateUsedTo: null,
    offenceOas:
      'Contrary to regulation 5 of the Carriage of Dangerous Goods and Use of Transportable Pressure Equipment Regulations 2009 and section 33(1)(c) and (3) of the Health and Safety at Work etc Act 1974.',
    offenceOasCy: null,
    businessUnit: null,
  },
  {
    offenceId: 33369,
    businessUnitId: null,
    cjsCode: 'FP12345',
    offenceTitle: 'Fixed penalty offence - Vehicle related',
    offenceTitleCy: null,
    dateUsedFrom: '2020-01-01T00:00:00',
    dateUsedTo: null,
    offenceOas: 'Fixed penalty notice offence under relevant regulations.',
    offenceOasCy: null,
    businessUnit: null,
  },
];

export const OPAL_FINES_OFFENCES_REF_DATA_MOCK: IOpalFinesOffencesRefData = {
  count: 18,
  refData: [
    {
      offence_id: 314441,
      get_cjs_code: 'AK123456',
      business_unit_id: 52,
      offence_title: 'ak test',
      offence_title_cy: null,
      date_used_from: '2022-11-12T00:00:00',
      date_used_to: null,
      offence_oas: 'act 1 section 12',
      offence_oas_cy: null,
    },
    {
      offence_id: 47883,
      get_cjs_code: 'CD09019',
      offence_title:
        'Carrier - vehicle carrying dangerous / pressurised goods with an inadequacy of fire extinguishers on the vehicle',
      date_used_from: '2009-07-01T00:00:00Z',
      offence_oas:
        'Contrary to regulation 5 of the Carriage of Dangerous Goods and Use of Transportable Pressure Equipment Regulations 2009 and section 33(1)(c) and (3) of the Health and Safety at Work etc Act 1974.',
      business_unit_id: 77,
      offence_title_cy: null,
      date_used_to: null,
      offence_oas_cy: null,
    },
    {
      offence_id: 33369,
      get_cjs_code: 'FP12345',
      business_unit_id: 77,
      offence_title: 'Fixed penalty offence - Vehicle related',
      offence_title_cy: null,
      date_used_from: '2020-01-01T00:00:00Z',
      date_used_to: null,
      offence_oas: 'Fixed penalty notice offence under relevant regulations.',
      offence_oas_cy: null,
    },
    {
      offence_id: 314683,
      get_cjs_code: 'CA03010D',
      business_unit_id: 22,
      offence_title: 'No Televison Licence',
      offence_title_cy: 'WWWWWWWWWWWWWWWWWWWWWW',
      date_used_from: '2001-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Contrary to section 363(2) and (4) of the Communications Act 2003.',
      offence_oas_cy: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
    {
      offence_id: 314201,
      get_cjs_code: 'GMMET001',
      business_unit_id: 22,
      offence_title: 'No Ticket on Metrolink',
      offence_title_cy: null,
      date_used_from: '2008-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Contrary to Regulation 4(1)(a) of the Greater Manchester Metrolink System Byelaws',
      offence_oas_cy: null,
    },
    {
      offence_id: 314203,
      get_cjs_code: 'GMMET001',
      business_unit_id: 1020,
      offence_title: 'No Ticket on Metrolink',
      offence_title_cy: null,
      date_used_from: '2008-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Contrary to Regulation 4(1)(a) of the Greater Manchester Metrolink System Byelaws',
      offence_oas_cy: null,
    },
    {
      offence_id: 314205,
      get_cjs_code: 'GMMET001',
      business_unit_id: 1037,
      offence_title: 'No Ticket on Metrolink',
      offence_title_cy: null,
      date_used_from: '2008-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Contrary to Regulation 4(1)(a) of the Greater Manchester Metrolink System Byelaws',
      offence_oas_cy: null,
    },
    {
      offence_id: 314321,
      get_cjs_code: 'GST001',
      business_unit_id: 52,
      offence_title: 'GST001',
      offence_title_cy: null,
      date_used_from: '2010-10-10T00:00:00',
      date_used_to: null,
      offence_oas: 'GST001',
      offence_oas_cy: null,
    },
    {
      offence_id: 314481,
      get_cjs_code: 'HU11001',
      business_unit_id: 1042,
      offence_title: 'Humberside By Law 001',
      offence_title_cy: null,
      date_used_from: '2011-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Act 1 Section 1',
      offence_oas_cy: null,
    },
    {
      offence_id: 314603,
      get_cjs_code: 'JF000001',
      business_unit_id: 52,
      offence_title: 'jf test',
      offence_title_cy: null,
      date_used_from: '2012-06-19T00:00:00',
      date_used_to: null,
      offence_oas: 'Act 1, Scene 1. A riverside.',
      offence_oas_cy: null,
    },
    {
      offence_id: 314281,
      get_cjs_code: 'LOC001',
      business_unit_id: 1042,
      offence_title: 'GST Local Offence Test',
      offence_title_cy: null,
      date_used_from: '2010-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Act & Section',
      offence_oas_cy: null,
    },
    {
      offence_id: 314361,
      get_cjs_code: 'NEWLOCOF',
      business_unit_id: 1042,
      offence_title: 'New Local Offence',
      offence_title_cy: null,
      date_used_from: '2010-03-18T00:00:00',
      date_used_to: null,
      offence_oas: 'Act & Section',
      offence_oas_cy: null,
    },
    {
      offence_id: 314723,
      get_cjs_code: 'NW01001',
      business_unit_id: 45,
      offence_title: "Fail to be long enough to fit as many words as necessary so that the tiltle isn't truncated ",
      offence_title_cy: null,
      date_used_from: '2014-01-01T00:00:00',
      date_used_to: null,
      offence_oas: 'Contrary to an Act',
      offence_oas_cy: null,
    },
    {
      offence_id: 314521,
      get_cjs_code: 'TEST12',
      business_unit_id: 52,
      offence_title: 'Test',
      offence_title_cy: null,
      date_used_from: '2011-10-11T00:00:00',
      date_used_to: null,
      offence_oas: 'Act 1 Section 12',
      offence_oas_cy: null,
    },
    {
      offence_id: 314561,
      get_cjs_code: 'TEST13',
      business_unit_id: 52,
      offence_title: 'test 13',
      offence_title_cy: null,
      date_used_from: '2011-11-07T00:00:00',
      date_used_to: null,
      offence_oas: 'act 1 s 13',
      offence_oas_cy: null,
    },
    {
      offence_id: 314643,
      get_cjs_code: 'TH68001',
      business_unit_id: 52,
      offence_title: 'fdfafsdsafsdf',
      offence_title_cy: null,
      date_used_from: '2014-10-11T00:00:00',
      date_used_to: null,
      offence_oas: 'fdsfasdf',
      offence_oas_cy: null,
    },
    {
      offence_id: 314601,
      get_cjs_code: 'TST50001',
      business_unit_id: 52,
      offence_title: 'Local Offence Blocked for Use',
      offence_title_cy: null,
      date_used_from: '2012-07-20T00:00:00',
      date_used_to: null,
      offence_oas: 'Act 5 Section 1',
      offence_oas_cy: null,
    },
    {
      offence_id: 314241,
      get_cjs_code: 'WE99999',
      business_unit_id: 22,
      offence_title: 'Overtaking on a Motorway without indicating',
      offence_title_cy: null,
      date_used_from: '2009-06-29T00:00:00',
      date_used_to: null,
      offence_oas: 'Motoring Act Contrary to the Motor Act.',
      offence_oas_cy: null,
    },
  ],
};

export const OPAL_FINES_LOCAL_JUSTICE_AREA_REF_DATA_MOCK: IOpalFinesLocalJusticeAreaRefData = {
  count: 5,
  refData: [
    {
      name: 'Asylum & Immigration Tribunal',
      postcode: 'LE1 6ZX',
      address_line_1: 'Arnhem Support Centre',
      local_justice_area_id: 9985,
      lja_code: '9985',
    },
    {
      name: "Avon & Somerset Magistrates' Court",
      postcode: 'BS1 3NU',
      address_line_1: "The Magistrates' Court",
      local_justice_area_id: 5735,
      lja_code: '1450',
    },
    {
      name: "Bedfordshire Magistrates' Court",
      postcode: 'LU1 5BL',
      address_line_1: 'Stuart Street',
      local_justice_area_id: 4165,
      lja_code: '1080',
    },
    {
      name: "Berkshire Magistrates' Court",
      postcode: 'RG1 7TQ',
      address_line_1: 'Civic Centre',
      local_justice_area_id: 4125,
      lja_code: '1920',
    },
    {
      name: "Birmingham and Solihull Magistrates' Court",
      postcode: 'B4 6QA',
      address_line_1: 'Victoria Law Courts',
      local_justice_area_id: 5004,
      lja_code: '2922',
    },
  ],
};

export const OPAL_FINES_RESULTS_REF_DATA_MOCK: IOpalFinesResultsRefData = {
  count: 8,
  refData: [
    {
      result_id: 'FCC',
      result_title: 'Criminal Courts Charge',
      result_title_cy: "Ffi'r Llysoedd Troseddol",
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CF',
      imposition_allocation_order: 6,
    },
    {
      result_id: 'FCOMP',
      result_title: 'Compensation',
      result_title_cy: 'Iawndal',
      active: true,
      result_type: 'Result',
      imposition_creditor: 'Any',
      imposition_allocation_order: 1,
    },
    {
      result_id: 'FCOST',
      result_title: 'Costs',
      result_title_cy: 'Costau',
      active: true,
      result_type: 'Result',
      imposition_creditor: '!CPS',
      imposition_allocation_order: 3,
    },
    {
      result_id: 'FCPC',
      result_title: 'Costs to Crown Prosecution Service',
      result_title_cy: 'Costau i Wasanaeth Erlyn y Goron',
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CPS',
      imposition_allocation_order: 3,
    },
    {
      result_id: 'FFR',
      result_title: 'FORFEITED RECOGNISANCE',
      result_title_cy: null,
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CF',
      imposition_allocation_order: 10,
    },
    {
      result_id: 'FO',
      result_title: 'Fine',
      result_title_cy: 'Dirwy',
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CF',
      imposition_allocation_order: 5,
    },
    {
      result_id: 'FVEBD',
      result_title: 'Vehicle Excise Back Duty',
      result_title_cy: 'Ôl-dreth ar y Dreth Cerbyd',
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CF',
      imposition_allocation_order: 8,
    },
    {
      result_id: 'FVS',
      result_title: 'Victim Surcharge',
      result_title_cy: 'Gordal Dioddefwr',
      active: true,
      result_type: 'Result',
      imposition_creditor: 'CF',
      imposition_allocation_order: 2,
    },
  ],
};

export const OPAL_FINES_RESULT_REF_DATA_MOCK: IOpalFinesResultRefData[] = [
  {
    result_id: 'REM',
    result_title: 'Reminder of Unpaid Fine',
    result_title_cy: 'Nodyn atgoffa terfynol am ddirwy heb ei thalu',
    result_type: 'Result',
    active: true,
    imposition: false,
    imposition_accruing: false,
    enforcement: true,
    enforcement_override: false,
    further_enforcement_warn: false,
    further_enforcement_disallow: false,
    enforcement_hold: false,
    requires_enforcer: false,
    generates_hearing: false,
    collection_order: false,
    extend_ttp_disallow: false,
    extend_ttp_preserve_last_enf: false,
    prevent_payment_card: false,
    lists_monies: false,
    result_parameters:
      '[{ "name":"reason", "prompt":"Reason", "type":"text", "min":1, "max":24, "language_dependent":"false" }]',
  },
  {
    result_id: 'FO',
    result_title: 'Fine',
    result_title_cy: 'Dirwy',
    result_type: 'Result',
    active: true,
    imposition_allocation_priority: 6,
    imposition_creditor: 'CF',
    imposition: true,
    imposition_category: 'Fines',
    imposition_accruing: false,
    enforcement: false,
    enforcement_override: false,
    further_enforcement_warn: false,
    further_enforcement_disallow: false,
    enforcement_hold: false,
    requires_enforcer: false,
    generates_hearing: false,
    collection_order: false,
    extend_ttp_disallow: false,
    extend_ttp_preserve_last_enf: false,
    prevent_payment_card: false,
    lists_monies: false,
  },
];

export const OPAL_FINES_MAJOR_CREDITOR_REF_DATA_MOCK: IOpalFinesMajorCreditorRefData = {
  count: 4,
  refData: [
    {
      account_number: null,
      business_unit_id: 77,
      creditor_account_id: null,
      creditor_account_type: null,
      from_suspense: null,
      hold_payout: null,
      last_changed_date: null,
      major_creditor_code: 'AGAL',
      major_creditor_id: 3855,
      major_creditor_party_id: null,
      name: 'Abellio Greater Anglia',
      postcode: null,
      prosecution_service: true,
    },
    {
      account_number: null,
      business_unit_id: 77,
      creditor_account_id: null,
      creditor_account_type: null,
      from_suspense: null,
      hold_payout: null,
      last_changed_date: null,
      major_creditor_code: 'ABJP',
      major_creditor_id: 3854,
      major_creditor_party_id: null,
      name: 'Aberdeen JP Court',
      postcode: null,
      prosecution_service: false,
    },
    {
      account_number: null,
      business_unit_id: 77,
      creditor_account_id: null,
      creditor_account_type: null,
      from_suspense: null,
      hold_payout: null,
      last_changed_date: null,
      major_creditor_code: 'ALDI',
      major_creditor_id: 3856,
      major_creditor_party_id: null,
      name: 'Aldi Stores Ltd',
      postcode: null,
      prosecution_service: false,
    },
    {
      account_number: null,
      business_unit_id: 77,
      creditor_account_id: null,
      creditor_account_type: null,
      from_suspense: null,
      hold_payout: null,
      last_changed_date: null,
      major_creditor_code: 'ARVA',
      major_creditor_id: 3858,
      major_creditor_party_id: null,
      name: 'Arriva Rail North',
      postcode: null,
      prosecution_service: false,
    },
  ],
};

export const OPAL_FINES_COURT_REF_DATA_MOCK: IOpalFinesCourtRefData = {
  count: 8,
  refData: [
    {
      court_id: 1865,
      business_unit_id: 61,
      court_code: 101,
      name: 'Historic Debt Database',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 1867,
      business_unit_id: 61,
      court_code: 998,
      name: 'Historic Debt Database',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 1866,
      business_unit_id: 61,
      court_code: 102,
      name: 'HISTORIC DEBT LODGE COURT',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 1868,
      business_unit_id: 61,
      court_code: 999,
      name: 'Port Talbot Justice Centre',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 770000000001,
      business_unit_id: 77,
      court_code: 104,
      name: 'Camberwell Green Magistrates Court',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 770000000002,
      business_unit_id: 77,
      court_code: 105,
      name: 'Southwark Crown Court',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 770000000003,
      business_unit_id: 77,
      court_code: 106,
      name: 'Inner London Crown Court',
      name_cy: null,
      national_court_code: null,
    },
    {
      court_id: 770000000004,
      business_unit_id: 77,
      court_code: 107,
      name: 'Woolwich Crown Court',
      name_cy: null,
      national_court_code: null,
    },
  ],
};
export const OPAL_FINES_PROSECUTOR_REF_DATA_MOCK: IOpalFinesProsecutorRefData = {
  count: 4,
  ref_data: [
    {
      prosecutor_id: 1865,
      prosecutor_name: 'Central ticket office',
      prosecutor_code: '998',
      address_line_1: null,
      address_line_2: null,
      address_line_3: null,
      address_line_4: null,
      address_line_5: null,
      postcode: null,
      end_date: null,
    },
    {
      prosecutor_id: 1223,
      prosecutor_name: 'Police force',
      prosecutor_code: '123',
      address_line_1: null,
      address_line_2: null,
      address_line_3: null,
      address_line_4: null,
      address_line_5: null,
      postcode: null,
      end_date: null,
    },
    {
      prosecutor_id: 3523,
      prosecutor_name: 'Other',
      prosecutor_code: '433',
      address_line_1: null,
      address_line_2: null,
      address_line_3: null,
      address_line_4: null,
      address_line_5: null,
      postcode: null,
      end_date: null,
    },
  ],
};
