export const MANUAL_ACCOUNT_CREATION_PERSONAL_DETAILS_STATE = {
  Title: null,
  Forenames: null,
  Surname: null,
  AddAlias: null,
  Aliases: [],
  DOB: null,
  NationalInsuranceNumber: null,
  AddressLine1: null,
  AddressLine2: null,
  AddressLine3: null,
  Postcode: null,
  VehicleMake: null,
  VehicleRegistrationMark: null,
};
