const MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_FIELDS = {
  businessUnit: null,
  defendantType: null,
};

export const MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_STATE = {
  formData: MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_FIELDS,
  snapshotFormData: MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_FIELDS,
  stateUnsavedChanges: false,
};
