import {
  MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_STATE,
  MANUAL_ACCOUNT_CREATION_COMPANY_DETAILS_STATE,
  MANUAL_ACCOUNT_CREATION_CONTACT_DETAILS_STATE,
  MANUAL_ACCOUNT_CREATION_EMPLOYER_DETAILS_STATE,
  MANUAL_ACCOUNT_CREATION_PARENT_GUARDIAN_DETAILS_STATE,
  MANUAL_ACCOUNT_CREATION_PERSONAL_DETAILS_STATE,
} from '@constants';

export const MANUAL_ACCOUNT_CREATION_STATE = {
  accountDetails: MANUAL_ACCOUNT_CREATION_ACCOUNT_DETAILS_STATE,
  employerDetails: MANUAL_ACCOUNT_CREATION_EMPLOYER_DETAILS_STATE,
  contactDetails: MANUAL_ACCOUNT_CREATION_CONTACT_DETAILS_STATE,
  parentGuardianDetails: MANUAL_ACCOUNT_CREATION_PARENT_GUARDIAN_DETAILS_STATE,
  personalDetails: MANUAL_ACCOUNT_CREATION_PERSONAL_DETAILS_STATE,
  companyDetails: MANUAL_ACCOUNT_CREATION_COMPANY_DETAILS_STATE,
  unsavedChanges: false,
  stateChanges: false,
};
