compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmPreapprovedPackages:
  - '@hmcts/opal-frontend-common'
  - '@hmcts/opal-frontend-common-node'
  - '@hmcts/opal-frontend-common-cypress'
  - '@hmcts/zephyr-automation-nodejs'

yarnPath: .yarn/releases/yarn-4.15.0.cjs
