export const DOM_ELEMENTS = {
  app: '#app-fines-acc-comments-add',
  heading: '.govuk-\!-margin-bottom-30',
  form: 'form.ng-untouched',
  commentField: '#facc_add_comment',
  freeText1Field: '#facc_add_free_text_1',
  freeText2Field: '#facc_add_free_text_2',
  freeText3Field: '#facc_add_free_text_3',
  submitButton: '#save-comments',
  cancelButton: '.govuk-link',
  errorSummary: '.govuk-error-summary',
  commentError: '#facc_add_comment-error-message',
  freeText1Error: '#facc_add_free_text_1-error-message',
  freeText2Error: '#facc_add_free_text_2-error-message',
  freeText3Error: '#facc_add_free_text_3-error-message',
  commentCharacterCount: '.govuk-form-group > :nth-child(4)',
  freeText1CharacterCount: '#facc_add_free_text_1-hint',
  freeText2CharacterCount: '#facc_add_free_text_2-hint',
  freeText3CharacterCount: '#facc_add_free_text_3-hint',
};
