import {
  IAbstractFormBaseFieldError,
  IAbstractFormBaseFieldErrors,
} from '@hmcts/opal-frontend-common/components/abstract/abstract-form-base/interfaces';

export interface IFinesAccDebtorAddAmendFieldErrors extends IAbstractFormBaseFieldErrors {
  facc_debtor_add_amend_title: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_forenames: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_surname: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_alias_forenames: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_alias_surname: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_dob: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_national_insurance_number: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_address_line_1: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_address_line_2: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_address_line_3: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_post_code: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_contact_email_address_1: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_contact_email_address_2: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_contact_telephone_number_mobile: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_contact_telephone_number_home: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_contact_telephone_number_business: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_vehicle_make: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_vehicle_registration_mark: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_language_preferences_document_language: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_language_preferences_hearing_language: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_company_name: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_reference: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_email_address: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_telephone_number: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_address_line_1: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_address_line_2: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_address_line_3: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_address_line_4: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_address_line_5: IAbstractFormBaseFieldError;
  facc_debtor_add_amend_employer_details_employer_post_code: IAbstractFormBaseFieldError;
}
