export const FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS = {
  accountConsolidated: 'Account consolidated',
  amountCreditedToMasterAccount: 'Amount credited to master account',
  case: 'Case:',
  chequeCancelled: 'Cheque cancelled',
  chequeDishonoured: 'Cheque dishonoured',
  chequeIssued: 'Cheque issued',
  chequeNumber: 'Cheque number:',
  chequeReissued: 'Cheque reissued',
  consolidated: 'Consolidated',
  created: 'Created:',
  dueBy: 'Due by:',
  daysInDefault: 'days in default',
  earliestDateOfRelease: 'Earliest date of release:',
  hearing: 'Hearing:',
  inFull: 'In full',
  instalments: 'Instalments:',
  lumpSum: 'Lump sum:',
  manualAdjustment: 'Manual adjustment',
  notYetWritten: 'Not yet written',
  old: 'Old:',
  new: 'New:',
  paid: 'Paid:',
  paymentReceived: 'Payment received',
  paymentReversed: 'Payment reversed',
  receivedFrom: 'Received from:',
  repaymentFromSuspense: 'Repayment from suspense',
  suspenseTransfer: 'Suspense transfer',
  transferFromSuspense: 'Transfer from suspense',
  transferredTo: 'Transferred to:',
  tfoIn: 'TFO in',
  tfoOut: 'TFO out',
  warrantNumber: 'Warrant number:',
  writeOff: 'Write-off',
  writeOffReversed: 'Write-off reversed',
};
