import { FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS } from './fines-acc-history-and-notes-details-labels.constant';

export const FINES_ACC_MAJOR_CREDITOR_HISTORY_AND_NOTES_TRANSACTION_TEMPLATES = {
  bacsPayment: {
    BACS: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.bacsPayment,
    RIBACS: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.bacsPaymentReissued,
    RTBACS: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.bacsPaymentReturned,
  },
  defendantAccount: {
    MADJ: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.manualAdjustment,
    PAYMNT: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.paymentReceived,
    REPAYC: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
    REPAYF: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
    REPAYM: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
    REPAYP: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
    REPAYV: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
    REPAYW: FINES_ACC_HISTORY_AND_NOTES_DETAILS_LABELS.repayment,
  },
} as const;
