export const FINES_ACC_HISTORY_AND_NOTES_DETAILS_FIELD_ALIASES = {
  accountNumber: ['details.accountNumber', 'details.account_number'],
  additionalInformation: ['details.additionalInformation'],
  amountImposed: ['details.amountImposed'],
  associatedRecordId: ['details.associatedRecordId', 'details.associated_record_id'],
  associatedRecordType: ['details.associatedRecordType', 'details.associated_record_type'],
  attributeName: ['details.attributeName'],
  caseReference: ['details.caseNumber'],
  creditorAccountNumber: ['details.accountNumber', 'details.account_number'],
  daysInDefault: ['details.daysInDefault', 'details.days_in_default'],
  defendantAccountId: ['details.defendantAccountId', 'details.defendant_account_id'],
  defendantAccountNumber: ['details.defendantAccountNumber', 'details.defendant_account_number'],
  effectiveDate: ['details.effective_date'],
  enforcementAction: ['details.enforcementAction'],
  enforcementReason: ['details.reason'],
  earliestDateOfRelease: ['details.earliestDateOfRelease'],
  hearingCourt: ['details.hearingCourt.court_name'],
  hearingDate: ['details.hearingDate'],
  impositionCode: ['details.impositionCode'],
  impositionDate: ['details.impositionDate'],
  instalmentAmount: ['details.instalment_amount'],
  instalmentLumpSum: ['details.lump_sum_amount'],
  instalmentPeriod: ['details.instalment_period.instalment_period_code'],
  noteText: ['details.noteText'],
  oldValue: ['details.oldValue'],
  originatorName: ['details.sendingCourt'],
  paymentMethod: ['details.paymentMethod.paymentMethod'],
  paymentReference: ['details.paymentReference', 'details.payment_reference'],
  paymentReferenceOnly: ['details.paymentReference'],
  reasonForExtension: ['details.reason_for_extension'],
  relatedAccountId: ['details.associatedRecordId', 'details.defendantAccountId'],
  status: [
    'details.status.defendantTransactionStatus',
    'details.status.creditorTransactionStatus',
    'details.status.defendant_transaction_status',
    'details.status.creditor_transaction_status',
  ],
  statusDate: ['details.statusDate', 'details.status_date'],
  termsType: ['details.payment_terms_type.payment_terms_type_code'],
  warrantNumber: ['details.warrantNumber'],
  writeOffDescription: ['details.writeOff.writeOffTypeDisplayName'],
  newValue: ['details.newValue'],
};
