export const FINES_ACC_HISTORY_AND_NOTES_DETAILS_TRANSACTION_TYPES = {
  bacs: 'BACS',
  cancelledCheque: 'CANCHQ',
  cheque: 'CHEQUE',
  consolidation: 'CONSOL',
  dishonouredCheque: 'DISHCQ',
  manualAdjustment: 'MADJ',
  payment: 'PAYMNT',
  repaymentFromSuspense: 'REPSUS',
  reversedPayment: 'REVPAY',
  reissuedCheque: 'RICHEQ',
  reissuedBacs: 'RIBACS',
  returnedBacs: 'RTBACS',
  reversedWriteOff: 'RVWOFF',
  suspenseTransfer: 'XFER',
  transferFromSuspense: 'FR-SUS',
  tfoIn: 'TFOIN',
  tfoOut: 'TFO',
  writeOff: 'WRTOFF',
} as const;
