export const FINES_ACC_HISTORY_AND_NOTES_DETAILS_SIMPLE_TRANSACTION_LABELS = {
  CFEES: 'Court Fee',
  FCC: 'Amount allocated to Fines Court Charge',
  FCMP: 'Amount allocated to Compensation from Scotland/NI',
  FCOST: 'Amount allocated to Costs',
  FCPC: 'Amount allocated to Crown Prosecutions Costs',
  FCST: 'Amount allocated to Cost from Scotland/NI',
  FCUEX: 'Amount allocated to Custom and Excise',
  FCOMP: 'Amount allocated to Compensation',
  FDCON: 'Amount allocated to Contribution to Form D Costs',
  FDCOST: 'Amount allocated to Form D Costs',
  FEES: 'Amount allocated to Fees',
  FFR: 'Amount allocated to Forfeited Recognizance',
  FINE: 'Amount allocated to Fines from Scotland/NI',
  FINES: 'Amount allocated to Fines',
  FIXPEN: 'Amount allocated to Fixed Penalty',
  FLAID: 'Amount allocated to Legal Aid Contribution',
  FNIA: 'Amount allocated to National Insurance Arrears',
  FO: 'Amount allocated to Fine Only',
  FOPR1: 'Amount allocated to Fine 1st Priority',
  FVEA: 'Amount allocated to Vehicle Excise Arrears',
  FVEBD: 'Amount allocated to Vehicle Excise Back Duty',
  FVS: 'Amount allocated to Victim Surcharge',
  FWEC: 'Amount allocated to Witness Expenses',
  LIFEES: 'Licensing Fee',
  PAID: 'Amount due to be paid',
  REPLIC: 'Repayment',
  WO611B: 'Amount allocated to Section 611B write-off',
} as const;
