openapi: 3.1.1
info:
  description: Opal Fines Service - Types
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  title: Opal Fines Service
  version: v0.0.1
components:
  schemas:
    BigInt:
      type: integer
      format: int64
