import { FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES } from './fines-acc-enf-action-add-control-names.constant';

export const FINES_ACC_ENF_ACTION_ADD_CLEAR_PAYMENT_TERMS_CONTROL_NAMES = [
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.paymentTerms,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.payByDate,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.instalmentAmount,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.instalmentPeriod,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.startDate,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.lumpSumAmount,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.daysInDefault,
  FINES_ACC_ENF_ACTION_ADD_FORM_CONTROL_NAMES.dateDaysInDefaultImposed,
] as const;
