import {
  IAbstractFormBaseFieldError,
  IAbstractFormBaseFieldErrors,
} from '@hmcts/opal-frontend-common/components/abstract/abstract-form-base/interfaces';

export interface IFinesAccPartyAddAmendConvertFieldErrors extends IAbstractFormBaseFieldErrors {
  facc_party_add_amend_convert_organisation_name: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_organisation_name_0: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_organisation_name_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_organisation_name_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_organisation_name_3: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_organisation_name_4: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_title: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_forenames: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_surname: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_forenames_0: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_surname_0: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_forenames_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_surname_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_forenames_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_surname_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_forenames_3: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_surname_3: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_forenames_4: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_alias_surname_4: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_dob: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_national_insurance_number: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_address_line_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_address_line_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_address_line_3: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_post_code: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_contact_email_address_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_contact_email_address_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_contact_telephone_number_mobile: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_contact_telephone_number_home: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_contact_telephone_number_business: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_vehicle_make: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_vehicle_registration_mark: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_language_preferences_document_language: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_language_preferences_hearing_language: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_company_name: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_reference: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_email_address: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_telephone_number: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_address_line_1: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_address_line_2: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_address_line_3: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_address_line_4: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_address_line_5: IAbstractFormBaseFieldError;
  facc_party_add_amend_convert_employer_post_code: IAbstractFormBaseFieldError;
}
