import { IFinesMacFixedPenaltyDetailsState } from '../interfaces/fines-mac-fixed-penalty-details-state.interface';

export const FINES_MAC_FIXED_PENALTY_DETAILS_STATE: IFinesMacFixedPenaltyDetailsState = {
  fm_fp_personal_details_title: null,
  fm_fp_personal_details_forenames: null,
  fm_fp_personal_details_surname: null,
  fm_fp_personal_details_dob: null,
  fm_fp_personal_details_address_line_1: null,
  fm_fp_personal_details_address_line_2: null,
  fm_fp_personal_details_address_line_3: null,
  fm_fp_personal_details_post_code: null,
  fm_fp_court_details_imposing_court_id: null,
  fm_fp_court_details_issuing_authority_id: null,
  fm_fp_account_comments_notes_comments: null,
  fm_fp_account_comments_notes_notes: null,
  fm_fp_account_comments_notes_system_notes: null,  
  fm_fp_language_preferences_document_language: null,
  fm_fp_language_preferences_hearing_language: null,
  fm_fp_offence_details_notice_number: null,
  fm_fp_offence_details_offence_type: null,
  fm_fp_offence_details_date_of_offence: null,
  fm_fp_offence_details_offence_id: null,
  fm_fp_offence_details_offence_cjs_code: null,
  fm_fp_offence_details_time_of_offence: null,
  fm_fp_offence_details_place_of_offence: null,
  fm_fp_offence_details_amount_imposed: null,
};
