/**
 * @file account.payment-terms.details.locators.ts
 * @description
 * Selector map for the **Payment terms** tab within Account Details,
 * including the Request payment card confirmation page.
 *
 * @remarks
 * - Prefers stable summary list row IDs generated by the GOV.UK summary list component.
 * - Confirmation page selectors are scoped to main content.
 */

export const AccountPaymentTermsDetailsLocators = {
  // ──────────────────────────────
  // Payment terms tab (Account Details)
  // ──────────────────────────────
  tab: {
    /** Root element for the Payment terms tab content. */
    root: 'app-fines-acc-defendant-details-payment-terms-tab',

    /** "Payment card last requested" summary value cell. */
    paymentCardLastRequestedValue: '#payment-termsPayment-card-last-requestedValue',

    /** "Payment card last requested" summary actions cell. */
    paymentCardLastRequestedActions: '#payment-termsPayment-card-last-requestedActions',

    /** Action link to request a payment card. */
    requestPaymentCardLink: '#payment-termsPayment-card-last-requestedActions a.govuk-link',
  },

  // ──────────────────────────────
  // Request payment card confirmation page
  // ──────────────────────────────
  confirmation: {
    /** Root scope for confirmation page content. */
    root: 'main[role="main"]',

    /** Page header for the confirmation page. */
    header: 'main[role="main"] h1.govuk-heading-l',

    /** Confirm button to submit the request. */
    confirmButton: 'main[role="main"] button.govuk-button:contains("Yes - request a payment card")',

    /** Cancel link to return to account details. */
    cancelLink: 'main[role="main"] a.govuk-link:contains("No - cancel")',
  },

  // ──────────────────────────────
  // Banners
  // ──────────────────────────────
  banners: {
    /** Success banner container on account details page. */
    success: 'opal-lib-moj-alert[type="success"]',

    /** Success banner text content. */
    successText: 'opal-lib-moj-alert-content-text',
  },
} as const;
