//describe("POST request body", () => {
const request = {
  draft_account_id: null,
  created_at: null,
  account_snapshot: null,
  account_status_date: null,
  business_unit_id: 77,
  submitted_by: 'L077JG',
  submitted_by_name: 'opal-test',
  account: {
    account_type: 'fine',
    defendant_type: 'adultOrYouthOnly',
    originator_name: "Berkshire Magistrates' Court",
    originator_id: 4125,
    prosecutor_case_reference: 'REF124',
    enforcement_court_id: 1863,
    collection_order_made: true,
    collection_order_made_today: null,
    collection_order_date: '2025-05-02',
    suspended_committal_date: null,
    payment_card_request: null,
    account_sentence_date: '2025-05-02',
    defendant: {
      company_flag: false,
      title: 'Ms',
      surname: 'REF',
      forenames: 'ref',
      company_name: null,
      dob: null,
      address_line_1: 'tesy',
      address_line_2: null,
      address_line_3: null,
      address_line_4: null,
      address_line_5: null,
      post_code: null,
      telephone_number_home: null,
      telephone_number_business: null,
      telephone_number_mobile: null,
      email_address_1: null,
      email_address_2: null,
      national_insurance_number: null,
      driving_licence_number: null,
      pnc_id: null,
      nationality_1: null,
      nationality_2: null,
      ethnicity_self_defined: null,
      ethnicity_observed: null,
      cro_number: null,
      occupation: null,
      gender: null,
      custody_status: null,
      prison_number: null,
      interpreter_lang: null,
      debtor_detail: {
        vehicle_make: null,
        vehicle_registration_mark: null,
        document_language: null,
        hearing_language: null,
        employee_reference: null,
        employer_company_name: null,
        employer_address_line_1: null,
        employer_address_line_2: null,
        employer_address_line_3: null,
        employer_address_line_4: null,
        employer_address_line_5: null,
        employer_post_code: null,
        employer_telephone_number: null,
        employer_email_address: null,
        aliases: null,
      },
      parent_guardian: null,
    },
    offences: [
      {
        date_of_sentence: '02/05/2025',
        imposing_court_id: 1863,
        offence_id: 33369,
        impositions: [
          {
            result_id: 'FO',
            amount_imposed: 200,
            amount_paid: 25,
            major_creditor_id: null,
            minor_creditor: null,
          },
        ],
      },
    ],
    fp_ticket_detail: null,
    payment_terms: {
      payment_terms_type_code: 'B',
      effective_date: '2025-05-01',
      instalment_period: null,
      lump_sum_amount: null,
      instalment_amount: null,
      default_days_in_jail: null,
      enforcements: null,
    },
    account_notes: null,
  },
  account_type: 'fine',
  account_status: 'Submitted',
  timeline_data: [
    {
      username: 'opal-test',
      status: 'Submitted',
      status_date: '2025-05-14',
      reason_text: null,
    },
  ],
};
//})
