export const DOM_ELEMENTS = {
  checkAccountButton: 'button[id="checkAccountButton"]',
  dataPage: 'opal-lib-govuk-summary-list',
  backLink: 'a.govuk-back-link',
  pageTitle: 'h1.govuk-heading-l',
  businessUnit: 'div[summaryListRowId="businessUnit"]',
  accountType: 'div[summaryListRowId="accountType"]',
  defendantType: 'div[summaryListRowId="defendantType"]',
  languagePreferences: 'div[summaryListRowId="languagePreferences"]',
  courtDetails: 'opal-lib-govuk-task-list[taskListId="courtDetails"]',
  defendantDetails: 'opal-lib-govuk-task-list[taskListId="defendantDetails"]',
  parentOrGuardianDetails: 'opal-lib-govuk-task-list[taskListId="parentOrGuardianDetails"]',
  offenceAndImpositionDetails: 'opal-lib-govuk-task-list[taskListId="offenceAndImpositionDetails"]',
  accountCommentsAndNotes: 'opal-lib-govuk-task-list[taskListId="accountCommentsAndNotes"]',
  deleteAccountLink: 'a.govuk-link.govuk-error-colour',
  contactDetails: 'opal-lib-govuk-task-list-item[taskListItemId="contactDetailsItem"]',
  employerDetails: 'opal-lib-govuk-task-list-item[taskListItemId="employerDetailsItem"]',
  companyDetails: 'opal-lib-govuk-task-list-item[taskListItemId="companyDetailsItem"]',
  personalDetails: 'opal-lib-govuk-task-list-item[taskListItemId="personalDetailsItem"]',
  parentGuardianDetails: 'opal-lib-govuk-task-list-item[taskListItemId="parentOrGuardianDetailsItem"]',
  offenceDetails: 'opal-lib-govuk-task-list-item[taskListItemId="offenceDetailsItem"]',
  paymentTerms: 'opal-lib-govuk-task-list-item[taskListItemId="paymentTermsItem"]',
  accountCommentsAndNotesItem: 'opal-lib-govuk-task-list-item[taskListItemId="accountCommentsAndNotesItem"]',
  CheckDetails: 'h2.govuk-heading-m',
  CheckDetailsText: 'p.govuk-body:contains("You cannot proceed until all required sections have been completed.")',

  //review status
  reviewComponent: 'app-fines-mac-review-account-history',
  status: 'strong[id = "status"]',
  reviewHistory: 'h3.govuk-heading-m',
  timeLine: 'div.moj-timeline__item',
  timeLineTitle: 'h2.moj-timeline__title',
  timelineAuthor: 'p.moj-timeline__byline',
  timelineDate: 'p.moj-timeline__date',
  timelineDescription: 'div.moj-timeline__description',
};
