export const DOM_ELEMENTS = {
  checkAccountButton: 'button[id="checkAccountButton"]',
  dataPage: 'app-govuk-summary-list',
  backLink: 'a.govuk-back-link',
  pageTitle: 'h1.govuk-heading-l',
  businessUnit: 'div[summaryListRowId="businessUnit"]',
  accountType: 'div[summaryListRowId="accountType"]',
  defendantType: 'div[summaryListRowId="defendantType"]',
  languagePreferences: 'div[summaryListRowId="languagePreferences"]',
  courtDetails: 'app-govuk-task-list[taskListId="courtDetails"]',
  defendantDetails: 'app-govuk-task-list[taskListId="defendantDetails"]',
  parentOrGuardianDetails: 'app-govuk-task-list[taskListId="parentOrGuardianDetails"]',
  offenceAndImpositionDetails: 'app-govuk-task-list[taskListId="offenceAndImpositionDetails"]',
  accountCommentsAndNotes: 'app-govuk-task-list[taskListId="accountCommentsAndNotes"]',
  deleteAccountLink: 'a.govuk-link.govuk-error-colour',
  contactDetails: 'app-govuk-task-list-item[taskListItemId="contactDetailsItem"]',
  employerDetails: 'app-govuk-task-list-item[taskListItemId="employerDetailsItem"]',
  companyDetails: 'app-govuk-task-list-item[taskListItemId="companyDetailsItem"]',
  personalDetails: 'app-govuk-task-list-item[taskListItemId="personalDetailsItem"]',
  parentGuardianDetails: 'app-govuk-task-list-item[taskListItemId="parentOrGuardianDetailsItem"]',
  offenceDetails: 'app-govuk-task-list-item[taskListItemId="offenceDetailsItem"]',
  paymentTerms: 'app-govuk-task-list-item[taskListItemId="paymentTermsItem"]',
  accountCommentsAndNotesItem: 'app-govuk-task-list-item[taskListItemId="accountCommentsAndNotesItem"]',
  CheckDetails: 'h2.govuk-heading-m',
  CheckDetailsText: 'p.govuk-body',
};
