nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FRONTEND_HOSTNAME: https://${SERVICE_FQDN}
    OPAL_API_URL: http://${SERVICE_NAME}-opal-fines-service
    OPAL_FINES_SERVICE_API_URL: http://${SERVICE_NAME}-opal-fines-service
    OPAL_USER_SERVICE_API_URL: https://opal-user-service.staging.platform.hmcts.net
    FEATURES_LAUNCH_DARKLY_ENABLED: false
    FEATURES_SSO_ENABLED: true
    SESSION_SAME_SITE: 'none'
    SESSION_DOMAIN: '.hmcts.net'
    CSRF_SAME_SITE: 'lax'
opal-fines-service:
  enabled: true
  java:
    releaseNameOverride: ${SERVICE_NAME}-opal-fines-service
    ingressHost: opal-fines-service-${SERVICE_FQDN}
    imagePullPolicy: Always
    devmemoryRequests: "1Gi"
    devcpuRequests: "250m"
    devmemoryLimits: "2Gi"
    devcpuLimits: "2500m"
    keyVaults:
      opal:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: AzureADTenantId
            alias: AAD_TENANT_ID
          - name: AzureADClientId
            alias: AAD_CLIENT_ID
          - name: AzureADClientSecret
            alias: AAD_CLIENT_SECRET
          - name: OpalTestUserPassword
            alias: OPAL_TEST_USER_PASSWORD
    environment:
      OPAL_FINES_DB_HOST: "{{ .Release.Name }}-postgresql"
      OPAL_FINES_DB_NAME: opal
      OPAL_FINES_DB_USERNAME: opal
      OPAL_FINES_DB_PASSWORD: opal
      OPAL_FINES_DB_OPTIONS: "?stringtype=unspecified"
      OPAL_FINES_DB_PORT: 5432
      RUN_DB_MIGRATION_ON_STARTUP: true
      OPAL_USER_SERVICE_API_URL: https://opal-user-service.staging.platform.hmcts.net
      OPAL_LEGACY_GATEWAY_URL: https://opal-legacy-db-stub.staging.platform.hmcts.net/opal
      OPAL_FRONTEND_URL: https://${SERVICE_FQDN}
      FLYWAY_LOCATIONS: classpath:db/migration/allEnvs, classpath:db/migration/devOnly
      FEATURES_APP_INSIGHTS_ENABLED: false
postgresql:
  enabled: true
  auth:
    username: opal
    password: opal
    database: opal
  primary:
    persistence:
      enabled: false
    resourcesPreset: small
