nodejs:
  applicationPort: 4000
  aadIdentityName: opal
  ingressHost: opal-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'sdshmctspublic.azurecr.io/opal/frontend:latest'
  keyVaults:
    opal:
      secrets:
        - AppInsightsInstrumentationKey
        - redis-connection-string
  environment:
    FEATURES_REDIS_ENABLED: true

redis:
  enabled: false