nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FRONTEND_HOSTNAME: https://${SERVICE_FQDN}
    OPAL_API_URL: https://opal-fines-service.staging.platform.hmcts.net