nodejs:
  applicationPort: 4000
  aadIdentityName: opal
  ingressHost: opal-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'sdshmctspublic.azurecr.io/opal/frontend:latest'
  keyVaults:
    opal:
      secrets:
        - AppInsightsInstrumentationKey
        - redis-connection-string
        - opal-frontend-session-secret
  environment:
    ALLOW_CONFIG_MUTATIONS: true
    FEATURES_REDIS_ENABLED: false
    OPAL_API_URL: https://opal-fines-service.{{ .Values.global.environment }}.platform.hmcts.net
    FRONTEND_HOSTNAME: https://opal-frontend.{{ .Values.global.environment }}.platform.hmcts.net

redis:
  enabled: false

opal-fines-service:
  enabled: false

postgresql:
  enabled: false
