export const DOM_ELEMENTS = {
  pageTitle: 'h1.govuk-heading-l',
  Legend: 'legend.govuk-fieldset__legend.govuk-fieldset__legend--m',
  addressLine1Label: 'label[for="fm_company_details_address_line_1"]',
  addressLine2Label: 'label[for="fm_company_details_address_line_2"]',
  addressLine3Label: 'label[for="fm_company_details_address_line_3"]',
  postcodeLabel: 'label[for="fm_company_details_postcode"]',
  companyNameLabel: 'label[for="fm_company_details_company_name"]',
  aliasCompanyName1Label: '#fm_company_details_add_alias-conditional > :nth-child(1) > .govuk-fieldset__legend',
  aliasCompanyName2Label: '#fm_company_details_add_alias-conditional > :nth-child(2) > .govuk-fieldset__legend',
  aliasCompanyName3Label: '#fm_company_details_add_alias-conditional > :nth-child(3) > .govuk-fieldset__legend',
  aliasCompanyName4Label: '#fm_company_details_add_alias-conditional > :nth-child(4) > .govuk-fieldset__legend',
  aliasCompanyName5Label: '#fm_company_details_add_alias-conditional > :nth-child(5) > .govuk-fieldset__legend',

  submitButton: 'button[type="submit"]',
  addContactDetailsButton: 'button:contains("Add contact details")',
  errorSummary: '.govuk-error-summary',
  cancelLink: 'a.govuk-link.button-link',

  companyNameInput: 'input[id="fm_company_details_company_name"]',
  additionalAlias: 'button[id="addAlias"]',
  addAlias: 'input[id="fm_company_details_add_alias"]',
  aliasRemoveLink: '.govuk-link:contains("Remove")',
  aliases: 'input[id="fm_company_details_aliases"]',
  aliasCompanyName1Input: 'input[id="fm_company_details_alias_company_name_0"]',
  aliasCompanyName2Input: 'input[id="fm_company_details_alias_company_name_1"]',
  aliasCompanyName3Input: 'input[id="fm_company_details_alias_company_name_2"]',
  aliasCompanyName4Input: 'input[id="fm_company_details_alias_company_name_3"]',
  aliasCompanyName5Input: 'input[id="fm_company_details_alias_company_name_4"]',
  addressLine1Input: 'input[id="fm_company_details_address_line_1"]',
  addressLine2Input: 'input[id="fm_company_details_address_line_2"]',
  addressLine3Input: 'input[id="fm_company_details_address_line_3"]',
  postcodeInput: 'input[id="fm_company_details_postcode"]',
};
