import { Component, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FinesService } from '@services/fines/fines-service/fines.service';
import { GovukBackLinkComponent } from '@components/govuk/govuk-back-link/govuk-back-link.component';
import { FINES_DRAFT_CHECK_AND_MANAGE_ROUTING_PATHS } from '../routing/constants/fines-draft-check-and-manage-routing-paths.constant';

@Component({
  selector: 'app-fines-draft-view-all-rejected',
  standalone: true,
  imports: [GovukBackLinkComponent],
  templateUrl: './fines-draft-view-all-rejected.component.html',
  styles: ``,
})
export class FinesDraftViewAllRejectedComponent {
  private readonly router = inject(Router);
  private readonly activatedRoute = inject(ActivatedRoute);
  private readonly finesService = inject(FinesService);

  /**
   * Navigates back to the inputter route within the fines draft routing paths.
   * The navigation includes the parent route and a fragment generated by the fines service.
   *
   * @returns {void}
   */
  public navigateBack(): void {
    this.router.navigate([`${FINES_DRAFT_CHECK_AND_MANAGE_ROUTING_PATHS.children.tabs}`], {
      relativeTo: this.activatedRoute.parent,
      fragment: this.finesService.finesDraftFragment(),
    });
  }
}
