import {
  FINES_MAC_CONTROLS_SURNAME as FINES_MAC_PERSONAL_DETAILS_CONTROLS_SURNAME,
  FINES_MAC_CONTROLS_FORENAMES as FINES_MAC_PERSONAL_DETAILS_CONTROLS_FORENAMES,
  FINES_MAC_CONTROLS_DOB as FINES_MAC_PERSONAL_DETAILS_CONTROLS_DOB,
  FINES_MAC_CONTROLS_ADD_ALIAS as FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADD_ALIAS,
  FINES_MAC_CONTROLS_ALIASES as FINES_MAC_PERSONAL_DETAILS_CONTROLS_ALIASES,
  FINES_MAC_CONTROLS_NATIONAL_INSURANCE_NUMBER as FINES_MAC_PERSONAL_DETAILS_CONTROLS_NATIONAL_INSURANCE_NUMBER,
  FINES_MAC_CONTROLS_ADDRESS_LINE_1 as FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_1,
  FINES_MAC_CONTROLS_ADDRESS_LINE_2 as FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_2,
  FINES_MAC_CONTROLS_POSTCODE as FINES_MAC_PERSONAL_DETAILS_CONTROLS_POSTCODE,
  FINES_MAC_CONTROLS_VEHICLE_MAKE as FINES_MAC_PERSONAL_DETAILS_CONTROLS_VEHICLE_MAKE,
  FINES_MAC_CONTROLS_VEHICLE_REGISTRATION_MARK as FINES_MAC_PERSONAL_DETAILS_CONTROLS_VEHICLE_REGISTRATION_MARK,
} from '../../constants/controls';
import {
  FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_3,
  FINES_MAC_PERSONAL_DETAILS_CONTROLS_TITLE,
} from './controls';

export const FINES_MAC_PERSONAL_DETAILS_FORM_GROUP = {
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_TITLE,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_FORENAMES,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_SURNAME,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADD_ALIAS,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_ALIASES,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_DOB,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_NATIONAL_INSURANCE_NUMBER,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_1,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_2,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_ADDRESS_LINE_3,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_POSTCODE,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_VEHICLE_MAKE,
  ...FINES_MAC_PERSONAL_DETAILS_CONTROLS_VEHICLE_REGISTRATION_MARK,
};
