import { ChangeDetectionStrategy, Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GovukBackLinkComponent } from '@hmcts/opal-frontend-common/components/govuk/govuk-back-link';
import { FinesDraftStore } from '../../stores/fines-draft.store';
import { FINES_DRAFT_CREATE_AND_MANAGE_ROUTING_PATHS } from '../routing/constants/fines-draft-create-and-manage-routing-paths.constant';
import { FinesDraftTableWrapperComponent } from '../../fines-draft-table-wrapper/fines-draft-table-wrapper.component';
import { FINES_DRAFT_TABLE_WRAPPER_SORT_DEFAULT } from '../../fines-draft-table-wrapper/constants/fines-draft-table-wrapper-table-sort.constants';
import { IFinesDraftTableWrapperTableData } from '../../fines-draft-table-wrapper/interfaces/fines-draft-table-wrapper-table-data.interface';
import { FinesDraftService } from '../../services/fines-draft.service';
import { FINES_ROUTING_PATHS } from '@routing/fines/constants/fines-routing-paths.constant';
import { FINES_MAC_ROUTING_PATHS } from '../../../fines-mac/routing/constants/fines-mac-routing-paths.constant';
import { FINES_DRAFT_ROUTE_DATA_KEYS } from '../../constants/fines-draft-route-data-keys.constant';
import { getResolvedDraftAccountsByKey } from '../../utils/fines-draft-route-data.utils';
import { FINES_DRAFT_RESOLVER_EMPTY_RESPONSE } from '../../routing/resolvers/constants/fines-draft-resolver-empty-response.constant';
import { FINES_DRAFT_TAB_FRAGMENT } from '../../constants/fines-draft-tab-fragments.constant';
import { FINES_ACCOUNT_TYPES } from '../../../constants/fines-account-types.constant';

@Component({
  selector: 'app-fines-draft-create-and-manage-view-all-rejected',
  standalone: true,
  imports: [GovukBackLinkComponent, FinesDraftTableWrapperComponent],
  templateUrl: './fines-draft-create-and-manage-view-all-rejected.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FinesDraftCreateAndManageViewAllRejectedComponent implements OnInit {
  private readonly router = inject(Router);
  private readonly activatedRoute = inject(ActivatedRoute);
  private readonly finesDraftStore = inject(FinesDraftStore);
  protected readonly finesDraftTabFragment = FINES_DRAFT_TAB_FRAGMENT;
  public readonly finesDraftService = inject(FinesDraftService);

  public tableSort = FINES_DRAFT_TABLE_WRAPPER_SORT_DEFAULT;
  public rejectedAccounts!: IFinesDraftTableWrapperTableData[];

  public readonly PATH_REVIEW_ACCOUNT = `${FINES_ROUTING_PATHS.root}/${FINES_MAC_ROUTING_PATHS.root}/${FINES_MAC_ROUTING_PATHS.children.reviewAccount}`;

  /**
   * Opens the selected rejected account in read-only review mode from the view-all list.
   *
   * @param row - The selected rejected account table row.
   */
  public onDefendantClick(row: IFinesDraftTableWrapperTableData): void {
    const draftAccountId = +row['Defendant id'];
    const accountType = row['Account type'];

    this.finesDraftStore.setViewAllAccounts(true);
    this.finesDraftStore.setAmend(true);

    const route =
      accountType === FINES_ACCOUNT_TYPES['Fixed Penalty']
        ? this.finesDraftService.PATH_REVIEW_ACCOUNT
        : this.finesDraftService.PATH_AMEND_ACCOUNT;

    this.finesDraftService.onDefendantClick(draftAccountId, route);
  }
  /**
   * Navigates back to the inputter route within the fines draft routing paths.
   * The navigation includes the parent route and a fragment generated by the fines service.
   *
   * @returns {void}
   */
  public navigateBack(): void {
    this.router.navigate([`${FINES_DRAFT_CREATE_AND_MANAGE_ROUTING_PATHS.children.tabs}`], {
      relativeTo: this.activatedRoute.parent,
      fragment: this.finesDraftStore.fragment(),
    });
  }

  /**
   * Populates rejected account table data from the route resolver and resets view-all state.
   */
  public ngOnInit(): void {
    const allRejectedAccounts =
      getResolvedDraftAccountsByKey(this.activatedRoute, FINES_DRAFT_ROUTE_DATA_KEYS.allRejectedAccounts) ??
      FINES_DRAFT_RESOLVER_EMPTY_RESPONSE;

    this.rejectedAccounts = this.finesDraftService.populateTableData(allRejectedAccounts);
    this.finesDraftStore.setViewAllAccounts(false);
  }
}
