import { ChangeDetectionStrategy, Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GovukBackLinkComponent } from '@hmcts/opal-frontend-common/components/govuk/govuk-back-link';
import { FinesDraftStore } from '../../stores/fines-draft.store';
import { FINES_DRAFT_CREATE_AND_MANAGE_ROUTING_PATHS } from '../routing/constants/fines-draft-create-and-manage-routing-paths.constant';
import { FinesDraftTableWrapperComponent } from '../../fines-draft-table-wrapper/fines-draft-table-wrapper.component';
import { FINES_DRAFT_TABLE_WRAPPER_SORT_DEFAULT } from '../../fines-draft-table-wrapper/constants/fines-draft-table-wrapper-table-sort-default.constant';
import { IOpalFinesDraftAccountsResponse } from '@services/fines/opal-fines-service/interfaces/opal-fines-draft-account-data.interface';
import { IFinesDraftTableWrapperTableData } from '../../fines-draft-table-wrapper/interfaces/fines-draft-table-wrapper-table-data.interface';
import { FinesDraftService } from '../../services/fines-draft.service';
import { FINES_ROUTING_PATHS } from '@routing/fines/constants/fines-routing-paths.constant';
import { FINES_MAC_ROUTING_PATHS } from '../../../fines-mac/routing/constants/fines-mac-routing-paths.constant';

@Component({
  selector: 'app-fines-draft-create-and-manage-view-all-rejected',
  standalone: true,
  imports: [GovukBackLinkComponent, FinesDraftTableWrapperComponent],
  templateUrl: './fines-draft-create-and-manage-view-all-rejected.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FinesDraftCreateAndManageViewAllRejectedComponent implements OnInit {
  private readonly router = inject(Router);
  private readonly activatedRoute = inject(ActivatedRoute);
  private readonly finesDraftStore = inject(FinesDraftStore);
  public readonly finesDraftService = inject(FinesDraftService);

  public tableSort = FINES_DRAFT_TABLE_WRAPPER_SORT_DEFAULT;
  public rejectedAccounts!: IFinesDraftTableWrapperTableData[];

  public readonly PATH_REVIEW_ACCOUNT = `${FINES_ROUTING_PATHS.root}/${FINES_MAC_ROUTING_PATHS.root}/${FINES_MAC_ROUTING_PATHS.children.reviewAccount}`;

  public onDefendantClick(draftAccountId: number): void {
    this.finesDraftStore.setViewAllAccounts(true);
    this.finesDraftStore.setAmend(false);

    this.finesDraftService.onDefendantClick(draftAccountId, this.PATH_REVIEW_ACCOUNT);
  }

  /**
   * Navigates back to the inputter route within the fines draft routing paths.
   * The navigation includes the parent route and a fragment generated by the fines service.
   *
   * @returns {void}
   */
  public navigateBack(): void {
    this.router.navigate([`${FINES_DRAFT_CREATE_AND_MANAGE_ROUTING_PATHS.children.tabs}`], {
      relativeTo: this.activatedRoute.parent,
      fragment: this.finesDraftStore.fragment(),
    });
  }

  public ngOnInit(): void {
    const allRejectedAccounts = this.activatedRoute.snapshot.data[
      'allRejectedAccounts'
    ] as IOpalFinesDraftAccountsResponse;

    this.rejectedAccounts = this.finesDraftService.populateTableData(allRejectedAccounts);
    this.finesDraftStore.setViewAllAccounts(false);
  }
}
