import { IFinesAccPartyAddAmendConvertState } from '../interfaces/fines-acc-party-add-amend-convert-state.interface';

export const FINES_ACC_PARTY_ADD_AMEND_CONVERT_STATE: IFinesAccPartyAddAmendConvertState = {
  facc_party_add_amend_convert_organisation_name: null,
  facc_party_add_amend_convert_title: null,
  facc_party_add_amend_convert_forenames: null,
  facc_party_add_amend_convert_surname: null,
  facc_party_add_amend_convert_individual_aliases: [],
  facc_party_add_amend_convert_organisation_aliases: [],
  facc_party_add_amend_convert_add_alias: null,
  facc_party_add_amend_convert_dob: null,
  facc_party_add_amend_convert_national_insurance_number: null,
  facc_party_add_amend_convert_address_line_1: null,
  facc_party_add_amend_convert_address_line_2: null,
  facc_party_add_amend_convert_address_line_3: null,
  facc_party_add_amend_convert_post_code: null,
  facc_party_add_amend_convert_contact_email_address_1: null,
  facc_party_add_amend_convert_contact_email_address_2: null,
  facc_party_add_amend_convert_contact_telephone_number_mobile: null,
  facc_party_add_amend_convert_contact_telephone_number_home: null,
  facc_party_add_amend_convert_contact_telephone_number_business: null,
  facc_party_add_amend_convert_vehicle_make: null,
  facc_party_add_amend_convert_vehicle_registration_mark: null,
  facc_party_add_amend_convert_language_preferences_document_language: null,
  facc_party_add_amend_convert_language_preferences_hearing_language: null,
  facc_party_add_amend_convert_employer_company_name: null,
  facc_party_add_amend_convert_employer_reference: null,
  facc_party_add_amend_convert_employer_email_address: null,
  facc_party_add_amend_convert_employer_telephone_number: null,
  facc_party_add_amend_convert_employer_address_line_1: null,
  facc_party_add_amend_convert_employer_address_line_2: null,
  facc_party_add_amend_convert_employer_address_line_3: null,
  facc_party_add_amend_convert_employer_address_line_4: null,
  facc_party_add_amend_convert_employer_address_line_5: null,
  facc_party_add_amend_convert_employer_post_code: null,
};
