export enum RoutingPaths {
  accountEnquiry = 'account-enquiry',
  accountEnquirySearch = 'search',
  accountEnquiryMatches = 'matches',
  accountEnquiryDetails = 'details/:defendantAccountId',
  accessDenied = 'access-denied',
  signIn = 'sign-in',
  signInStub = 'sign-in-stub',
  dashboard = 'dashboard',
  manualAccountCreation = 'manual-account-creation',
  manualAccountCreationAccountDetails = 'account-details',
  manualAccountCreationCreateAccount = 'create-account',
  manualAccountCreationEmployerDetails = 'employer-details',
  manualAccountCreationContactDetails = 'contact-details',
  manualAccountCreationCompanyDetails = 'company-details',
  manualAccountCreationParentGuardianDetails = 'parent-guardian-details',
  manualAccountCreationPersonalDetails = 'personal-details',
  manualAccountCreationOffenceDetails = 'offence-details',
  manualAccountCreationCourtDetails = 'court-details',
  manualAccountCreationAccountCommentsNotes = 'account-comments-notes',
}
